export const quotes = {
  happy: [
    // English Quotes
    {
      quote: "Here's looking at you, kid.",
      movie: "Casablanca",
      movieOriginal: "Casablanca",
      character: "Rick Blaine",
      characterOriginal: "Rick Blaine",
    },
    {
      quote: "May the Force be with you.",
      movie: "Star Wars",
      movieOriginal: "Star Wars",
      character: "Han Solo",
      characterOriginal: "Han Solo",
    },
    {
      quote: "I'm on top of the world!",
      movie: "White Heat",
      movieOriginal: "White Heat",
      character: "Cody Jarrett",
      characterOriginal: "Cody Jarrett",
    },
    {
      quote: "Life is like a box of chocolates.",
      movie: "Forrest Gump",
      movieOriginal: "Forrest Gump",
      character: "Forrest Gump",
      characterOriginal: "Forrest Gump",
    },
    {
      quote: "Hakuna Matata!",
      movie: "The Lion King",
      movieOriginal: "The Lion King",
      character: "Timon",
      characterOriginal: "Timon",
    },
    {
      quote: "There's no place like home.",
      movie: "The Wizard of Oz",
      movieOriginal: "The Wizard of Oz",
      character: "Dorothy Gale",
      characterOriginal: "Dorothy Gale",
    },
    // Cantonese Quotes
    {
      quote: "做人如果無夢想，同條鹹魚有咩分別啊？",
      romanization:
        "Zou6 jan4 jyu4 gwo2 mou5 mung6 soeng2, tung4 tiu4 haam4 jyu2 jau5 me1 fan1 bit6 aa3?",
      translation:
        "If a person has no dreams, how are they different from a salted fish?",
      movie: "Shaolin Soccer",
      movieOriginal: "少林足球",
      character: "Sing",
      characterOriginal: "星",
    },
    {
      quote: "我同你講，人生最緊要係開心！",
      romanization:
        "Ngo5 tung4 nei5 gong2, jan4 sang1 zeoi3 gan2 jiu3 hai6 hoi1 sam1!",
      translation:
        "I’m telling you, the most important thing in life is to be happy!",
      movie: "The God of Cookery",
      movieOriginal: "食神",
      character: "Stephen Chow",
      characterOriginal: "周星馳",
    },
    {
      quote: "有信心就一定會贏！",
      romanization: "Jau5 seon3 sam1 zau6 jat1 ding6 wui5 jeng4!",
      translation: "With confidence, you’ll definitely win!",
      movie: "Kung Fu Hustle",
      movieOriginal: "功夫",
      character: "Sing",
      characterOriginal: "星",
    },
    {
      quote: "今日我好開心，因為我終於做到我想做嘅嘢！",
      romanization:
        "Gam1 jat6 ngo5 hou2 hoi1 sam1, jan1 wai6 ngo5 zung1 jyu1 zou6 dou3 ngo5 soeng2 zou6 ge3 je5!",
      translation:
        "Today I’m so happy because I finally did what I wanted to do!",
      movie: "Fight Back to School",
      movieOriginal: "逃學威龍",
      character: "Star Chow",
      characterOriginal: "周星",
    },
    {
      quote: "笑一笑，世界更美妙！",
      romanization: "Siu3 jat1 siu3, sai3 gaai3 gang3 mei5 miu6!",
      translation: "Smile a little, and the world becomes more wonderful!",
      movie: "Flirting Scholar",
      movieOriginal: "唐伯虎點秋香",
      character: "Tong Pak Fu",
      characterOriginal: "唐伯虎",
    },
    {
      quote: "人生有咩唔開心，笑一笑就得！",
      romanization:
        "Jan4 sang1 jau5 me1 m4 hoi1 sam1, siu3 jat1 siu3 zau6 dak1!",
      translation: "What’s there to be unhappy about in life? Just smile!",
      movie: "King of Comedy",
      movieOriginal: "喜劇之王",
      character: "Yin Tin Sau",
      characterOriginal: "尹天仇",
    },
  ],
  sad: [
    // English Quotes
    {
      quote: "I'm king of the world!",
      movie: "Titanic",
      movieOriginal: "Titanic",
      character: "Jack Dawson",
      characterOriginal: "Jack Dawson",
    },
    {
      quote: "I'll never let go, Jack.",
      movie: "Titanic",
      movieOriginal: "Titanic",
      character: "Rose DeWitt",
      characterOriginal: "Rose DeWitt",
    },
    {
      quote: "Why so serious?",
      movie: "The Dark Knight",
      movieOriginal: "The Dark Knight",
      character: "The Joker",
      characterOriginal: "The Joker",
    },
    {
      quote: "I wish I knew how to quit you.",
      movie: "Brokeback Mountain",
      movieOriginal: "Brokeback Mountain",
      character: "Jack Twist",
      characterOriginal: "Jack Twist",
    },
    {
      quote: "It's not fair!",
      movie: "The Princess Bride",
      movieOriginal: "The Princess Bride",
      character: "Buttercup",
      characterOriginal: "Buttercup",
    },
    {
      quote: "After all, tomorrow is another day!",
      movie: "Gone with the Wind",
      movieOriginal: "Gone with the Wind",
      character: "Scarlett O'Hara",
      characterOriginal: "Scarlett O'Hara",
    },
    // Cantonese Quotes
    {
      quote: "那個時代已過去。屬於那個時代的一切，都不存在了。",
      romanization:
        "Naa5 go3 si4 doi6 ji5 gwo3 heoi3. Suk6 jyu1 naa5 go3 si4 doi6 dik1 jat1 cai3, dou1 bat1 cyun4 zoi6 liu5.",
      translation:
        "That era is gone. Everything that belongs to that era no longer exists.",
      movie: "In the Mood for Love",
      movieOriginal: "花樣年華",
      character: "Narrator",
      characterOriginal: "旁白",
    },
    {
      quote: "人生有幾多個十年？",
      romanization: "Jan4 sang1 jau5 gei2 do1 go3 sap6 nin4?",
      translation: "How many decades are there in a lifetime?",
      movie: "Days of Being Wild",
      movieOriginal: "阿飛正傳",
      character: "Yuddy",
      characterOriginal: "旭仔",
    },
    {
      quote: "我會唔會再見到你？",
      romanization: "Ngo5 wui5 m4 wui5 zoi3 gin3 dou2 nei5?",
      translation: "Will I ever see you again?",
      movie: "Chungking Express",
      movieOriginal: "重慶森林",
      character: "Cop 663",
      characterOriginal: "警察663",
    },
    {
      quote: "有啲嘢，失去了就唔會再返嚟。",
      romanization:
        "Jau5 di1 je5, sat1 heoi3 liu5 zau6 m4 wui5 zoi3 faan1 lei4.",
      translation: "Some things, once lost, will never come back.",
      movie: "Comrades: Almost a Love Story",
      movieOriginal: "甜蜜蜜",
      character: "Li Xiao-jun",
      characterOriginal: "黎小軍",
    },
    {
      quote: "點解每次我想要嘅嘢，都要失去？",
      romanization:
        "Dim2 gaai2 mui5 ci3 ngo5 soeng2 jiu3 ge3 je5, dou1 jiu3 sat1 heoi3?",
      translation: "Why do I have to lose everything I want every time?",
      movie: "Fallen Angels",
      movieOriginal: "墮落天使",
      character: "Wong Chi-ming",
      characterOriginal: "黃志明",
    },
    {
      quote: "我一個人，點解要咁多痛苦？",
      romanization: "Ngo5 jat1 go3 jan4, dim2 gaai2 jiu3 gam3 do1 tung3 fu2?",
      translation: "I’m just one person, why do I have to suffer so much?",
      movie: "Lost and Found",
      movieOriginal: "天涯海角",
      character: "Lam",
      characterOriginal: "林",
    },
  ],
  angry: [
    // English Quotes
    {
      quote: "You talking to me?",
      movie: "Taxi Driver",
      movieOriginal: "Taxi Driver",
      character: "Travis Bickle",
      characterOriginal: "Travis Bickle",
    },
    {
      quote: "Say hello to my little friend!",
      movie: "Scarface",
      movieOriginal: "Scarface",
      character: "Tony Montana",
      characterOriginal: "Tony Montana",
    },
    {
      quote: "I'm as mad as hell!",
      movie: "Network",
      movieOriginal: "Network",
      character: "Howard Beale",
      characterOriginal: "Howard Beale",
    },
    {
      quote: "Get out of my house!",
      movie: "Home Alone",
      movieOriginal: "Home Alone",
      character: "Kevin McCallister",
      characterOriginal: "Kevin McCallister",
    },
    {
      quote: "You can’t handle the truth!",
      movie: "A Few Good Men",
      movieOriginal: "A Few Good Men",
      character: "Col. Nathan Jessup",
      characterOriginal: "Col. Nathan Jessup",
    },
    {
      quote: "I want my money back!",
      movie: "The Godfather",
      movieOriginal: "The Godfather",
      character: "Vito Corleone",
      characterOriginal: "Vito Corleone",
    },
    // Cantonese Quotes
    {
      quote: "出嚟行，遲早要還！",
      romanization: "Ceot1 lei4 haang4, ci4 zou2 jiu3 waan4!",
      translation:
        "If you step into this world, sooner or later you’ll have to pay it back!",
      movie: "Infernal Affairs",
      movieOriginal: "無間道",
      character: "Hon Sam",
      characterOriginal: "韓琛",
    },
    {
      quote: "你同我講，邊個夠膽同我爭！",
      romanization:
        "Nei5 tung4 ngo5 gong2, bin1 go3 gau3 daam2 tung4 ngo5 zaang1!",
      translation: "Tell me, who dares to fight me!",
      movie: "Election",
      movieOriginal: "黑社會",
      character: "Lok",
      characterOriginal: "樂",
    },
    {
      quote: "我同你講，唔好搞亂我！",
      romanization: "Ngo5 tung4 nei5 gong2, m4 hou2 gaau2 lyun6 ngo5!",
      translation: "I’m telling you, don’t mess with me!",
      movie: "Police Story",
      movieOriginal: "警察故事",
      character: "Chan Ka-Kui",
      characterOriginal: "陳家駒",
    },
    {
      quote: "你再唔走，我同你唔客氣！",
      romanization: "Nei5 zoi3 m4 zau2, ngo5 tung4 nei5 m4 haak3 hei3!",
      translation: "If you don’t leave now, I won’t be polite with you!",
      movie: "Drunken Master",
      movieOriginal: "醉拳",
      character: "Wong Fei-hung",
      characterOriginal: "黃飛鴻",
    },
    {
      quote: "我唔係怕你，我係唔想同你嘈！",
      romanization:
        "Ngo5 m4 hai6 paa3 nei5, ngo5 hai6 m4 soeng2 tung4 nei5 cou4!",
      translation:
        "I’m not afraid of you, I just don’t want to argue with you!",
      movie: "Young and Dangerous",
      movieOriginal: "古惑仔",
      character: "Chan Ho-nam",
      characterOriginal: "陳浩南",
    },
    {
      quote: "你試下再講多句，我即刻同你翻臉！",
      romanization:
        "Nei5 si3 haa5 zoi3 gong2 do1 geoi3, ngo5 zik1 hak1 tung4 nei5 faan1 lim5!",
      translation: "Say one more word, and I’ll turn on you right now!",
      movie: "Fight Back to School II",
      movieOriginal: "逃學威龍II",
      character: "Star Chow",
      characterOriginal: "周星",
    },
  ],
  surprised: [
    // English Quotes
    {
      quote: "I see dead people.",
      movie: "The Sixth Sense",
      movieOriginal: "The Sixth Sense",
      character: "Cole Sear",
      characterOriginal: "Cole Sear",
    },
    {
      quote: "You're gonna need a bigger boat.",
      movie: "Jaws",
      movieOriginal: "Jaws",
      character: "Chief Brody",
      characterOriginal: "Chief Brody",
    },
    {
      quote: "No way!",
      movie: "Wayne's World",
      movieOriginal: "Wayne's World",
      character: "Wayne Campbell",
      characterOriginal: "Wayne Campbell",
    },
    {
      quote: "I am your father!",
      movie: "Star Wars: The Empire Strikes Back",
      movieOriginal: "Star Wars: The Empire Strikes Back",
      character: "Darth Vader",
      characterOriginal: "Darth Vader",
    },
    {
      quote: "What did you say?!",
      movie: "Back to the Future",
      movieOriginal: "Back to the Future",
      character: "Marty McFly",
      characterOriginal: "Marty McFly",
    },
    {
      quote: "This can’t be happening!",
      movie: "Jurassic Park",
      movieOriginal: "Jurassic Park",
      character: "Dr. Alan Grant",
      characterOriginal: "Dr. Alan Grant",
    },
    // Cantonese Quotes
    {
      quote: "點解會係咁樣？",
      romanization: "Dim2 gaai2 wui5 hai6 gam2 joeng2?",
      translation: "Why is it like this?",
      movie: "A Simple Life",
      movieOriginal: "桃姐",
      character: "Roger",
      characterOriginal: "羅杰",
    },
    {
      quote: "你話咩？真係唔敢信！",
      romanization: "Nei5 waa6 me1? Zan1 hai6 m4 gam2 seon3!",
      translation: "What did you say? I can’t believe it!",
      movie: "The Killer",
      movieOriginal: "喋血雙雄",
      character: "Ah Jong",
      characterOriginal: "小莊",
    },
    {
      quote: "吓？原来係咁！",
      romanization: "Haa2? Jyun4 loi4 hai6 gam2!",
      translation: "Huh? So that’s how it is!",
      movie: "Hard Boiled",
      movieOriginal: "辣手神探",
      character: "Tequila",
      characterOriginal: "龍",
    },
    {
      quote: "乜嘢？真係你做嘅？",
      romanization: "Mat1 je5? Zan1 hai6 nei5 zou6 ge3?",
      translation: "What? You really did it?",
      movie: "Project A",
      movieOriginal: "A計劃",
      character: "Dragon Ma",
      characterOriginal: "馬如龍",
    },
    {
      quote: "吓！點解會有咁嘅事？",
      romanization: "Haa2! Dim2 gaai2 wui5 jau5 gam2 ge3 si6?",
      translation: "What! How could something like this happen?",
      movie: "Ashes of Time",
      movieOriginal: "東邪西毒",
      character: "Ouyang Feng",
      characterOriginal: "歐陽鋒",
    },
    {
      quote: "吓！邊度嚟咁多錢？",
      romanization: "Haa2! Bin1 dou6 lei4 gam3 do1 cin2?",
      translation: "What! Where did all this money come from?",
      movie: "God of Gamblers",
      movieOriginal: "賭神",
      character: "Ko Chun",
      characterOriginal: "高進",
    },
  ],
  neutral: [
    // English Quotes
    {
      quote: "Houston, we have a problem.",
      movie: "Apollo 13",
      movieOriginal: "Apollo 13",
      character: "Jim Lovell",
      characterOriginal: "Jim Lovell",
    },
    {
      quote: "Just keep swimming.",
      movie: "Finding Nemo",
      movieOriginal: "Finding Nemo",
      character: "Dory",
      characterOriginal: "Dory",
    },
    {
      quote: "I’ll be back.",
      movie: "The Terminator",
      movieOriginal: "The Terminator",
      character: "The Terminator",
      characterOriginal: "The Terminator",
    },
    {
      quote: "Keep the change, ya filthy animal.",
      movie: "Home Alone",
      movieOriginal: "Home Alone",
      character: "Pizza Guy",
      characterOriginal: "Pizza Guy",
    },
    {
      quote: "Elementary, my dear Watson.",
      movie: "The Adventures of Sherlock Holmes",
      movieOriginal: "The Adventures of Sherlock Holmes",
      character: "Sherlock Holmes",
      characterOriginal: "Sherlock Holmes",
    },
    {
      quote: "The name’s Bond. James Bond.",
      movie: "Dr. No",
      movieOriginal: "Dr. No",
      character: "James Bond",
      characterOriginal: "James Bond",
    },
    // Cantonese Quotes
    {
      quote: "講你又唔聽，聽你又唔懂，懂你又唔做。",
      romanization:
        "Gong2 nei5 jau6 m4 teng1, teng1 nei5 jau6 m4 dung2, dung2 nei5 jau6 m4 zou6.",
      translation:
        "I talk but you don’t listen. You listen but don’t understand. You understand but don’t act.",
      movie: "The Bare-Footed Kid",
      movieOriginal: "赤腳小子",
      character: "Unknown",
      characterOriginal: "未知",
    },
    {
      quote: "人生如戲，戲如人生。",
      romanization: "Jan4 sang1 jyu4 hei3, hei3 jyu4 jan4 sang1.",
      translation: "Life is like a play, and a play is like life.",
      movie: "Echoes of the Rainbow",
      movieOriginal: "歲月神偷",
      character: "Narrator",
      characterOriginal: "旁白",
    },
    {
      quote: "有啲嘢，唔使問咁多。",
      romanization: "Jau5 di1 je5, m4 sai2 man6 gam3 do1.",
      translation: "Some things don’t need so many questions.",
      movie: "Exiled",
      movieOriginal: "放逐",
      character: "Blaze",
      characterOriginal: "火",
    },
    {
      quote: "人生就係一場遊戲，點玩都得。",
      romanization:
        "Jan4 sang1 zau6 hai6 jat1 coeng4 jau4 hei3, dim2 waan2 dou1 dak1.",
      translation: "Life is just a game, you can play it however you want.",
      movie: "The Longest Nite",
      movieOriginal: "暗花",
      character: "Sam",
      characterOriginal: "森",
    },
    {
      quote: "做人要低調，先至唔會有咁多麻煩。",
      romanization:
        "Zou6 jan4 jiu3 dai1 diu6, sin1 zi3 m4 wui5 jau5 gam3 do1 maa4 faan4.",
      translation:
        "To live, keep a low profile, then you won’t have so much trouble.",
      movie: "Running Out of Time",
      movieOriginal: "暗戰",
      character: "Cheung",
      characterOriginal: "張",
    },
    {
      quote: "凡事有因有果，唔使太執著。",
      romanization: "Faan4 si6 jau5 jan1 jau5 gwo2, m4 sai2 taai3 zap1 zoek6.",
      translation:
        "Everything has a cause and effect, no need to be too attached.",
      movie: "One Nite in Mongkok",
      movieOriginal: "旺角黑夜",
      character: "Lai Fu",
      characterOriginal: "來福",
    },
  ],
};
